name: Merging of feature Branch into Develop Branch
on:
  push:
    branches:
      - 'feature**'

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    name: Tests
    if: ${{ contains(github.event.head_commit.message, 'DEPLOY') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Merge Develop into feature branch
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch:  ${{ github.ref }}


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: ng test --no-watch --browsers=ChromeHeadless --code-coverage | tee test-output.txt

      - name: Check coverage is at least 60%
        run: |
          STATEMENTS_COVERAGE=$(grep -Po 'Statements\s*:\s*\K\d+' test-output.txt)
          echo "Statements coverage is $STATEMENTS_COVERAGE%"
          if [ "$STATEMENTS_COVERAGE" -lt 60 ]; then
            echo "Coverage is below 60%"
            exit 1
          fi

      # - name: Merge feature branch into Develop
      #   uses: tukasz/direct-merge-action@master
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     source-branch: ${{ github.ref }}
      #     target-branch: develop
