name: Creation of Release Branhc and PR to main
on:
  push:
    branches:
      - 'develop'

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    name: Tests
    if: ${{ contains(github.event.head_commit.message, 'RELEASE') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.13 ]

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: ./test
        run: pytest --cov=src -v -s --cov-fail-under=65

      - name: Sanitize commit message for branch name
        id: sanitize_message
        run: |
          # Sanitize the commit message to create a valid branch name
          BRANCH_NAME=$(echo "${{ github.event.head_commit.message }}" | sed -e 's/[^a-zA-Z0-9._-]/-/g' | cut -c1-50)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create a new release branch from develop
        run: |
          git checkout -b $BRANCH_NAME develop
          git push origin $BRANCH_NAME
